FROM python:3.9-slim

WORKDIR /app

COPY data_downloader_image/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY source/data_downloader.py data_downloader.py
CMD ["python", "data_downloader.py"]